[package]
name = "contract-rps"
version = "0.1.0"
edition = "2024"

[dependencies]
library = { path = "../library" }
macros = { path = "../macros" }
serde = "1.0"
serde_json = "1.0"
ethnum = { version = "1.5.0" }
hex = "0.4.3"

[lib]
crate-type = ["cdylib"]
