# docker/docker-compose.yml
services:
  yugabyted:
    image: yugabytedb/yugabyte:latest
    container_name: yb-single
    restart: unless-stopped

    # each array element becomes one argv item → no quoting hell
    command:
      - bin/yugabyted
      - start
      - --daemon=false
      - --base_dir=/var/lib/ybd
      - --ysql_port=5433
      - --tserver_flags=ysql_sequence_cache_minval=10000   # 10 k serial gap
      - --ui=false

    ports:
      - "5433:5433"   # YSQL (Postgres wire)
      - "7000:7000"   # Master UI – comment out if you don’t need it
      # - "9000:9000" # T-server UI (enable & add flag `--tserver_http_port=9000` if desired)

    volumes:
      - yb_data:/var/lib/ybd

volumes:
  yb_data:
